files:
  - source: /site2/docs/*.md
    translation: /site2/docs/%two_letters_code%/%original_file_name%
  - source: /site2/website/pages/en/*.js
    translation: /site2/website/pages/%two_letters_code%/%original_file_name%
  - source: /site2/website/blog/*.md
    translation: /site2/website/blog/%two_letters_code%/%original_file_name%
  - source: /site/docs/latest/
    translation: /site/docs/%two_letters_code%/%original_file_name%
